title: This is Teddy!
description: Happy Hacking
baseurl: /

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks]

permalink: /:year/:month/:day/:title/
encoding: utf-8
links:
  - name:     About
    url:      /about
  - name:     Blog
    url:      /
  - name:     Email
    url:      mailto:ivan.wang1004@gmail.com
    external: true
  - name:     GitHub
    url:      http://github.com/teddy1004
    external: true
