name: This is Teddy!
description: Happy Hacking
baseurl: /
meta_description: "编程小菜鸟的所思所想"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks]

paginate: 10

permalink: /:year/:month/:day/:title
encoding: utf-8
# Details for the RSS feed generator
url:            'teddy1004.github.io'
author:         'Teddy'
